### ISSUE TITLE
최근 업데이트 날짜가 6월로 표시되는 문제

### ISSUE THREAD

**Issue by utilForever** [DirtyBoyz/opgc_backend#46]
![image](https://user-images.githubusercontent.com/5622661/126412733-1469ad4f-1ee4-47b5-b370-cd3b5cb79437.png)

**Comment by JAY-Chan9yu** [comment]
@utilForever 감사합니다!!:D 요번 주말안에 수정 해보겠습니다~

**Comment by JAY-Chan9yu** [comment]
수정완료!
