### ISSUE TITLE
Github API 에러에 의한 업데이트 불가 이슈

### ISSUE THREAD

**Issue by KevinTheRainmaker** [DirtyBoyz/opgc_backend#65]
<img width="716" alt="image" src="https://user-images.githubusercontent.com/76294398/165653568-6f280827-c378-4890-bbf9-bc926efb6eda.png">

개인 프로필 상단 리프레쉬 버튼을 통해 업데이트할 경우 위와 같은 문구가 뜨면서 업데이트가 되지 않습니다. 
해당 이슈는 약 일주일 전 처음 발견하였는데 지금까지 동일하게 발생하고 있고, 리드미에 부착된 태그 및 사이트 내 최근업데이트 일자가 9일 전 시점에 멈춰있습니다.

**Comment by JAY-Chan9yu** [comment]
@KevinTheRainmaker 안녕하세요! 먼저 불편을 드려죄송합니다!
해당이슈는 제가 배포시 환경변수 수정을 하였는데, 잘못된 값이 들어가서 생긴 이슈였습니다. 
토큰값이 잘못들어가 깃헙 api가 호출되지 않았었고 현재 해결하였습니다!
감사합니다!
